up:
	docker compose up -d --remove-orphans

down:
	docker compose down

mac-up:
	docker-compose up -d --remove-orphans

mac-down:
	docker-compose down

dev:
	npm run start:dev

build:
	npm run build

deploy:
	sh scripts/deploy-local.sh

log:
	sh scripts/log.sh